project_id = "vehcghewfnjkwlwmmrix"
[functions.generate-post-ideas]
enabled = true
verify_jwt = true
import_map = "./functions/generate-post-ideas/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-post-ideas/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-post-ideas/*.html" ]

[functions.generate-and-publish]
enabled = true
verify_jwt = false
import_map = "./functions/generate-and-publish/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-and-publish/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-and-publish/*.html" ]

[functions.process-publish-queue]
enabled = true
verify_jwt = false
import_map = "./functions/process-publish-queue/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-publish-queue/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-publish-queue/*.html" ]

[functions.image-trigger]
enabled = true
verify_jwt = false
import_map = "./functions/image-trigger/deno.json"
entrypoint = "./functions/image-trigger/index.ts"

[functions.process-image-queue]
enabled = true
verify_jwt = false
import_map = "./functions/process-image-queue/deno.json"
entrypoint = "./functions/process-image-queue/index.ts"

[functions.generate-content-v3]
enabled = true
verify_jwt = false
import_map = "./functions/generate-content-v3/deno.json"
entrypoint = "./functions/generate-content-v3/index.ts"

[functions.wordpress-posts]
enabled = true
verify_jwt = false
import_map = "./functions/wordpress-posts/deno.json"
entrypoint = "./functions/wordpress-posts/index.ts"

[functions.generate-image]
enabled = true
verify_jwt = false
import_map = "./functions/generate-image/deno.json"
entrypoint = "./functions/generate-image/index.ts"
