project_id = "vehcghewfnjkwlwmmrix"
[functions.generate-post-ideas]
enabled = true
verify_jwt = false
import_map = "./functions/generate-post-ideas/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-post-ideas/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-post-ideas/*.html" ]

[functions.get-sitemap-pages]
enabled = true
verify_jwt = false
import_map = "./functions/get-sitemap-pages/deno.json"
entrypoint = "./functions/get-sitemap-pages/index.ts"

[functions.crawl-website-pages]
enabled = true
verify_jwt = false
import_map = "./functions/crawl-website-pages/deno.json"
entrypoint = "./functions/crawl-website-pages/index.ts"

[functions.suggest-key-content]
enabled = true
verify_jwt = false
import_map = "./functions/suggest-key-content/deno.json"
entrypoint = "./functions/suggest-key-content/index.ts"

[functions.scrape-content]
enabled = true
verify_jwt = false
import_map = "./functions/scrape-content/deno.json"
entrypoint = "./functions/scrape-content/index.ts"

[functions.detect-website-language]
enabled = true
verify_jwt = false
import_map = "./functions/detect-website-language/deno.json"
entrypoint = "./functions/detect-website-language/index.ts"

[functions.generate-and-publish]
enabled = true
verify_jwt = true
import_map = "./functions/generate-and-publish/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-and-publish/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-and-publish/*.html" ]

[functions.process-publish-queue]
enabled = true
verify_jwt = true
import_map = "./functions/process-publish-queue/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-publish-queue/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-publish-queue/*.html" ]

[functions.check-scheduled-posts]
enabled = true
verify_jwt = false
import_map = "./functions/check-scheduled-posts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-scheduled-posts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-scheduled-posts/*.html" ]

[functions.reset-stalled-jobs]
enabled = true
verify_jwt = false
import_map = "./functions/reset-stalled-jobs/deno.json"
entrypoint = "./functions/reset-stalled-jobs/index.ts"

[functions.wordpress-posts]
enabled = true
verify_jwt = false
import_map = "./functions/wordpress-posts/deno.json"
entrypoint = "./functions/wordpress-posts/index.ts"

[functions.stripe-portal]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-portal/deno.json"
entrypoint = "./functions/stripe-portal/index.ts"
