[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./dist"
include = ["**/*"]

[build.environment]
NODE_VERSION = "18"

[env.production]
name = "contentgardener"
route = "contentgardener.ai/*" 